version: '3'

tasks:
  dev:frontend:
    desc: "Start React frontend development server"
    cmds:
      - cd apps/main-app/frontend && npm run dev
    
  dev:marketing:
    desc: "Start Quarto marketing site with Netlify functions"
    dir: apps/marketing
    cmds:
      - netlify dev
      
  dev:all:
    desc: "Start both frontend and marketing sites simultaneously"
    cmds:
      - |
        echo "🚀 Starting both servers..."
        echo "🔗 Frontend: http://localhost:5173"
        echo "🔗 Marketing: http://localhost:8888"
        echo ""
        echo "Building marketing site first..."
        (cd apps/marketing && quarto render)
        echo ""
        echo "Press Ctrl+C to stop all servers"
        echo ""
        
        # Start frontend in background (from root to access .env)
        (cd apps/main-app/frontend && npm run dev) &
        FRONTEND_PID=$!
        
        # Start marketing in background  
        (cd apps/marketing && netlify dev) &
        MARKETING_PID=$!
        
        # Wait for both processes
        wait $FRONTEND_PID $MARKETING_PID

  dev:frontend-bg:
    desc: "Start React frontend in background"
    dir: apps/main-app/frontend
    cmds:
      - npm run dev
    internal: true

  dev:marketing-bg:
    desc: "Start Quarto marketing site with Netlify functions in background"
    dir: apps/marketing
    cmds:
      - netlify dev
    internal: true

  install:
    desc: "Install all dependencies"
    cmds:
      - task: install:frontend
      - task: install:python

  install:frontend:
    desc: "Install frontend dependencies"
    dir: apps/main-app/frontend
    cmds:
      - npm install

  install:python:
    desc: "Install Python dependencies"
    cmds:
      - echo "Activating virtual environment..."
      - source venv/bin/activate && pip install -r packages/ai-clients/requirements.txt
      - cd packages/cc-template && source ../../venv/bin/activate && uv sync

  setup:python:
    desc: "Set up Python virtual environment"
    cmds:
      - python3 -m venv venv
      - source venv/bin/activate && pip install --upgrade pip
      - echo "✅ Python virtual environment created at ./venv"
      - echo "Run 'source venv/bin/activate' to activate it"

  build:frontend:
    desc: "Build React frontend for production"
    dir: apps/main-app/frontend
    cmds:
      - npm run build

  build:marketing:
    desc: "Build Quarto marketing site for production"
    dir: apps/marketing
    cmds:
      - quarto render

  build:all:
    desc: "Build both frontend and marketing sites"
    deps:
      - build:frontend
      - build:marketing

  lint:frontend:
    desc: "Lint React frontend code"
    dir: apps/main-app/frontend
    cmds:
      - npm run lint

  test:python:
    desc: "Run Python tests"
    dir: packages/cc-template
    cmds:
      - source ../../venv/bin/activate && pytest

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -rf apps/main-app/frontend/dist
      - rm -rf apps/marketing/docs
      - echo "✅ Build artifacts cleaned"

  status:
    desc: "Show status of all services"
    cmds:
      - echo "🔍 Checking service status..."
      - echo "Frontend (React){{":"}} http{{":"}}//localhost{{":"}}5173"
      - echo "Marketing (Quarto){{":"}} http{{":"}}//localhost{{":"}}4710"