[build]
  command = "echo 'Using pre-built files'"
  publish = "apps/marketing/docs"
  functions = "apps/marketing/netlify/functions"

[dev]
  command = "quarto preview --port 4710"
  targetPort = 4710

[[redirects]]
  from = "/success.html"
  to = "/.netlify/functions/verify-session"
  status = 302